/**
 * @author RaffyRod (https://github.com/RaffyRod)
 */

import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref<'en' | 'es'>(
    (localStorage.getItem('language') as 'en' | 'es') || 'en'
  );

  const translations = {
    en: {
      title: 'QA Web Analyzer',
      subtitle: 'Accessibility Analysis Tool',
      urlPlaceholder: 'Enter URL (e.g., http://localhost:3000 or https://example.com)',
      analyzeBtn: 'Analyze',
      analyzing: '🔍 Analyzing page...',
      analysisOptions: 'Analysis Options',
      elementsToCheck: 'Elements to Check',
      attributesToCheck: 'Attributes to Check',
      images: 'Images',
      links: 'Links',
      buttons: 'Buttons',
      inputs: 'Inputs',
      elementsWithRole: 'Elements with Role',
      headings: 'Headings (h1-h6)',
      tables: 'Tables',
      formElements: 'Form Elements (select, textarea)',
      altText: 'Alt Text',
      ariaLabel: 'aria-label',
      ariaLabelledby: 'aria-labelledby',
      ariaDescribedby: 'aria-describedby',
      ariaHidden: 'aria-hidden',
      ariaExpanded: 'aria-expanded',
      ariaControls: 'aria-controls',
      ariaCurrent: 'aria-current',
      ariaRequired: 'aria-required',
      ariaInvalid: 'aria-invalid',
      ariaChecked: 'aria-checked',
      ariaDisabled: 'aria-disabled',
      ariaPressed: 'aria-pressed',
      ariaBusy: 'aria-busy',
      ariaLive: 'aria-live',
      autocomplete: 'autocomplete',
      required: 'required',
      tabIndex: 'tabindex',
      lang: 'lang',
      labelElements: '<label> elements',
      titleAttribute: 'title attribute',
      focusStates: 'Focus States (WCAG 2.2 AA)',
      href: 'href',
      selectAll: 'All',
      deselectAll: 'None',
      showMore: 'Show More',
      showLess: 'Show Less',
      search: 'Search...',
      searchPlaceholder: 'Search attributes and elements...',
      typeMore: 'Type at least 3 characters to search',
      clearSearch: 'Clear search',
      noResults: 'No results found',
      summary: 'Summary',
      errorUrlRequired: 'Please enter a URL',
      errorInvalidUrl: 'URL must start with http:// or https://',
      errorAnalysisFailed: 'Failed to analyze page',
      totalImages: 'Total Images',
      imagesWithoutAlt: 'Images Without Alt',
      imagesWithoutFocusState: 'Images Without Focus State',
      totalLinks: 'Total Links',
      linksWithoutAccessibility: 'Links Without Accessibility',
      linksWithoutFocusState: 'Links Without Focus State',
      totalButtons: 'Total Buttons',
      buttonsWithoutAccessibility: 'Buttons Without Accessibility',
      buttonsWithoutFocusState: 'Buttons Without Focus State',
      totalInputs: 'Total Inputs',
      inputsWithoutAccessibility: 'Inputs Without Accessibility',
      totalRoles: 'Total Roles',
      rolesWithoutAccessibility: 'Roles Without Accessibility',
      filters: 'Filters',
      showMissing: 'Show Missing',
      showHasAttributes: 'Show Has Attributes',
      showSections: 'Show Sections',
      noImages: 'No images found',
      noLinks: 'No links found',
      noButtons: 'No buttons found',
      noInputs: 'No inputs found',
      noRoles: 'No roles found',
      noText: 'No text',
      none: 'None',
      missing: 'Missing',
      htmlCode: 'HTML Code',
      expand: 'Expand',
      collapse: 'Collapse',
      exportAsPDF: 'Export as PDF',
      exporting: 'Exporting...',
      exported: 'Exported',
      errorNoReport: 'No report available to export',
      errorExportFailed: 'Export failed',
      stop: 'Stop',
      analysisCancelled: 'Analysis cancelled',
      analysisCompleted: 'Analysis completed',
      analysisCompletedMessage: 'The page analysis has been completed successfully.',
      exportPDF: 'Export PDF',
      elementsToInclude: 'Elements to Include',
      resultsStatus: 'Results Status',
      passed: 'Passed',
      failed: 'Failed',
      exportStatusInfo:
        'Select which results to include in the PDF. You can export only passed items, only failed items, or both.',
      additionalOptions: 'Additional Options',
      includeSummary: 'Include Summary',
      includeScreenshots: 'Include Screenshots',
      includeHTML: 'Include HTML Code',
      cancel: 'Cancel',
    },
    es: {
      title: 'QA Web Analyzer',
      subtitle: 'Herramienta de Análisis de Accesibilidad',
      urlPlaceholder: 'Ingresa URL (ej: http://localhost:3000 o https://example.com)',
      analyzeBtn: 'Analizar',
      analyzing: '🔍 Analizando página...',
      analysisOptions: 'Opciones de Análisis',
      elementsToCheck: 'Elementos a Verificar',
      attributesToCheck: 'Atributos a Verificar',
      images: 'Imágenes',
      links: 'Enlaces',
      buttons: 'Botones',
      inputs: 'Inputs',
      elementsWithRole: 'Elementos con Role',
      headings: 'Encabezados (h1-h6)',
      tables: 'Tablas',
      formElements: 'Elementos de Formulario (select, textarea)',
      altText: 'Texto Alt',
      ariaLabel: 'aria-label',
      ariaLabelledby: 'aria-labelledby',
      ariaDescribedby: 'aria-describedby',
      ariaHidden: 'aria-hidden',
      ariaExpanded: 'aria-expanded',
      ariaControls: 'aria-controls',
      ariaCurrent: 'aria-current',
      ariaRequired: 'aria-required',
      ariaInvalid: 'aria-invalid',
      ariaChecked: 'aria-checked',
      ariaDisabled: 'aria-disabled',
      ariaPressed: 'aria-pressed',
      ariaBusy: 'aria-busy',
      ariaLive: 'aria-live',
      autocomplete: 'autocomplete',
      required: 'required',
      tabIndex: 'tabindex',
      lang: 'lang',
      labelElements: 'elementos <label>',
      titleAttribute: 'atributo title',
      focusStates: 'Estados de Foco (WCAG 2.2 AA)',
      href: 'href',
      selectAll: 'Todo',
      deselectAll: 'Ninguno',
      showMore: 'Mostrar Más',
      showLess: 'Mostrar Menos',
      search: 'Buscar...',
      searchPlaceholder: 'Buscar atributos y elementos...',
      typeMore: 'Escribe al menos 3 caracteres para buscar',
      clearSearch: 'Limpiar búsqueda',
      noResults: 'No se encontraron resultados',
      summary: 'Resumen',
      errorUrlRequired: 'Por favor ingresa una URL',
      errorInvalidUrl: 'La URL debe comenzar con http:// o https://',
      errorAnalysisFailed: 'Error al analizar la página',
      totalImages: 'Total de Imágenes',
      imagesWithoutAlt: 'Imágenes Sin Alt',
      imagesWithoutFocusState: 'Imágenes Sin Estado de Foco',
      totalLinks: 'Total de Enlaces',
      linksWithoutAccessibility: 'Enlaces Sin Accesibilidad',
      linksWithoutFocusState: 'Enlaces Sin Estado de Foco',
      totalButtons: 'Total de Botones',
      buttonsWithoutAccessibility: 'Botones Sin Accesibilidad',
      buttonsWithoutFocusState: 'Botones Sin Estado de Foco',
      totalInputs: 'Total de Inputs',
      inputsWithoutAccessibility: 'Inputs Sin Accesibilidad',
      totalRoles: 'Total de Roles',
      rolesWithoutAccessibility: 'Roles Sin Accesibilidad',
      filters: 'Filtros',
      showMissing: 'Mostrar Faltantes',
      showHasAttributes: 'Mostrar Con Atributos',
      showSections: 'Mostrar Secciones',
      noImages: 'No se encontraron imágenes',
      noLinks: 'No se encontraron enlaces',
      noButtons: 'No se encontraron botones',
      noInputs: 'No se encontraron inputs',
      noRoles: 'No se encontraron roles',
      noText: 'Sin texto',
      none: 'Ninguno',
      missing: 'Faltante',
      htmlCode: 'Código HTML',
      expand: 'Expandir',
      collapse: 'Contraer',
      exportAsPDF: 'Exportar como PDF',
      exporting: 'Exportando...',
      exported: 'Exportado',
      errorNoReport: 'No hay reporte disponible para exportar',
      errorExportFailed: 'Error al exportar',
      stop: 'Detener',
      analysisCancelled: 'Análisis cancelado',
      analysisCompleted: 'Análisis completado',
      analysisCompletedMessage: 'El análisis de la página se ha completado exitosamente.',
      exportPDF: 'Exportar PDF',
      elementsToInclude: 'Elementos a Incluir',
      resultsStatus: 'Estado de Resultados',
      passed: 'Aprobado',
      failed: 'Fallido',
      exportStatusInfo:
        'Selecciona qué resultados incluir en el PDF. Puedes exportar solo elementos aprobados, solo fallidos, o ambos.',
      additionalOptions: 'Opciones Adicionales',
      includeSummary: 'Incluir Resumen',
      includeScreenshots: 'Incluir Capturas',
      includeHTML: 'Incluir Código HTML',
      cancel: 'Cancelar',
    },
  };

  function setLanguage(lang: 'en' | 'es') {
    currentLanguage.value = lang;
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  }

  function t(key: string): string {
    return translations[currentLanguage.value][key as keyof typeof translations.en] || key;
  }

  return {
    currentLanguage,
    translations,
    setLanguage,
    t,
  };
});
